// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtcNN9PPPUv45E6ibCm2uGRGVaXqfj7U',
    appId: '1:415437229635:web:08716c2a220ff34e358ef6',
    messagingSenderId: '415437229635',
    projectId: 'ecom-5b01d',
    authDomain: 'ecom-5b01d.firebaseapp.com',
    storageBucket: 'ecom-5b01d.appspot.com',
    measurementId: 'G-H6LX9K8W78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-CfPXA7L3MGo2ZQyaXXOte88l8payEM',
    appId: '1:415437229635:android:c201f04efaac1ef3358ef6',
    messagingSenderId: '415437229635',
    projectId: 'ecom-5b01d',
    storageBucket: 'ecom-5b01d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCvMTOJb3IGmz1yq1xMs__QnMhVbPlxI',
    appId: '1:415437229635:ios:15b9bbae5aeb6bed358ef6',
    messagingSenderId: '415437229635',
    projectId: 'ecom-5b01d',
    storageBucket: 'ecom-5b01d.appspot.com',
    iosBundleId: 'com.example.userPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCvMTOJb3IGmz1yq1xMs__QnMhVbPlxI',
    appId: '1:415437229635:ios:15b9bbae5aeb6bed358ef6',
    messagingSenderId: '415437229635',
    projectId: 'ecom-5b01d',
    storageBucket: 'ecom-5b01d.appspot.com',
    iosBundleId: 'com.example.userPanel',
  );

}